
package web.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IHotelServiceWeb2", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHotelServiceWeb2 {


    /**
     * 
     * @param password
     * @param dateArrivee
     * @param telephone
     * @param dateDepart
     * @param nom
     * @param numeroChambre
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "effectueReservation", targetNamespace = "http://service/", className = "web.service.client.EffectueReservation")
    @ResponseWrapper(localName = "effectueReservationResponse", targetNamespace = "http://service/", className = "web.service.client.EffectueReservationResponse")
    @Action(input = "http://service/IHotelServiceWeb2/effectueReservationRequest", output = "http://service/IHotelServiceWeb2/effectueReservationResponse")
    public String effectueReservation(
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "numeroChambre", targetNamespace = "")
        int numeroChambre,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "telephone", targetNamespace = "")
        String telephone,
        @WebParam(name = "dateArrivee", targetNamespace = "")
        XMLGregorianCalendar dateArrivee,
        @WebParam(name = "dateDepart", targetNamespace = "")
        XMLGregorianCalendar dateDepart);

}
